### ISSUE TITLE
Roadmap to PyStan 3

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#177]
# 3.0.0rc1 (around Feb 25)
- [x] Finalize the user interfaces guidelines design document. (in particular, the draws-are-trailing-axis bit) (see https://github.com/stan-dev/design-docs/pull/25)
- [x] Resolve all issues created before ca. 2020-12-01 in this repository and in httpstan.
- [x] Replace the current pystan repository with this repository.
- [x] Add a link to the old PyStan 2 documentation
- [x] Announce pending deprecation on the Stan forum. Give ~1 month notice.
- [x] ~Email/open issues in packages which depend on PyStan, ask them to pin to \~2.~ (Too much work.)
- [x] Make rc1 release about a month after deprecation announcement.

# 3.0.0 (around March 25)
- [x] Add FAQ section
- [x] Write release notes
- [x] Before release, remove all mention on "beta" from docs
- [x] Mark PyStan 2 github repo as archived.

**Comment by riddell-stan** [comment]
I'll close this now. There's a PR with the last round of documentation updates here: #239
